version: '3'
services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - /root/docker/nginx/logs:/var/log/nginx
    networks:
      - elk
    restart: always

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.15.2
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"
    expose:
      - "9200"
    networks:
      - elk
    restart: always

  kibana:
    image: docker.elastic.co/kibana/kibana:7.15.2
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    networks:
      - elk
    restart: always

  filebeat:
    image: docker.elastic.co/beats/filebeat:7.15.2
    volumes:
      - /root/docker/filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml
      - /root/docker/nginx/logs:/var/log/nginx
    user: root
    networks:
      - elk
    restart: always

networks:
  elk:
    driver: bridge
